### ISSUE TITLE
Adding new Cell in the latest version

### ISSUE THREAD

**Issue by nahidrahmati** [UvaCsl/HemoCell#11]
I have a problem with new version of Hemocell. In previous version, I had added "CTC" as a new cell to the pipeflow.cpp file and defined CTC.h and CTC.cpp in the mechanics folder (that was successful). In this new version, when I want to add it, I will receive undefined reference error in the hemocell.h (line 125), although I added required file in the mechanics folder. In addition, I searched how you added PltSimpleModel, and tried exactly like it, but I have got this error again. Can you please help me to define CTC in new version of hemocell?

**Comment by MaxvdKolk** [comment]
Dear @nahidrahmati,

This is most-likely due to the changes in the build system we have added in the more recent versions. Any additional `*.h` and `*.cpp` files have to be registered explicitly in the `CMakeLists.txt` file of the considered example. For an example, you can look at the [`capillary/CMakeLists.txt`](https://github.com/UvaCsl/HemoCell/blob/master/examples/capillary/CMakeLists.txt#L10) of [`examples/capillary`](https://github.com/UvaCsl/HemoCell/tree/master/examples/capillary) where two additional files are included (`bifurcation.h, bifurcation.cpp` and `wedge.h, wedge.cpp`). 

For your example, assuming the files are name `CTC.h` and `CTC.cpp`, the line in your `CMakeLists.txt` will look like 

```
add_executable(${EXEC_NAME} "CTC" "${CMAKE_CURRENT_SOURCE_DIR}/${MAIN}.cpp")
```

Please let me know if this resolves your issue.

**Comment by nahidrahmati** [comment]
Thanks, 
That works.
