### ISSUE TITLE
RBC_HO resolution and checkpoint problem

### ISSUE THREAD

**Issue by ErenC1** [UvaCsl/HemoCell#98]
Hi!

On Hemocell 2.7, when I change RBC_HO resolution(minNumTriangles) from 2k to 3k nothing happens, number of trianges stays the same (checking through mean_edge, it stays same). Its not just this interval, there are some "dead" intervals. Is this a bug? I tried to find where RBC points are generated but couldn't find it. But I am sure there is a problem.
And when I increase resolution to 6k, at checkpoint simulation stucks (happened few times, I'm running simulations without checkpoint now). This is definitely a bug.

Best,
Eren.

**Comment by gzavo** [comment]
Hi Eren,

The RBC resolution is the expected behaviour. You can't pick arbitrary resolutions, to ensure symmetry, it is based on recursive subdivision. For details on how an RBC is discretised follow up this function:
https://github.com/UvaCsl/HemoCell/blob/d91698721f7a06166cb6ac8d22fa2f2f4baa4ed7/helper/meshGeneratingFunctions.hh#L214
The theory is described in "Ramanujan, S., & Pozrikidis, C. (1998). Deformation of liquid capsules enclosed by elastic membranes in simple shear flow: large deformations and the effect of fluid viscosities. Journal of fluid mechanics, 361, 117-143."

The checkpointing might have a problem at that high vertex counts (though I don't see a direct reason for it), we have never tested it. 

Bests,
Gabor

**Comment by ErenC1** [comment]
Hi!

Thank you for the answers. About checkpoint, in 20k timesteps, size of the solution files was about 1.5 GB and checkpoint folders size was also near 1.5 GB. IDK if its about the size and writing speed, but OFC I am using SSD so it shouldn't be a problem and I waited near half an hour (twice) before interrupting the run. 

Looks like I need to use "RBC from stl", I want to ask few question before starting to use it.
I think they are "surface mesh" file but not volume. I am assuming that inner edges are generated by coupling the points from the opposide of the STL. In documentation it is mentioned that STL file needs to be ASCII but not binary, but "RBC.stl" file inside the "cell shapes" example is binary, therefore I couldn't check it to be sure. But even if I don't use inner edges it should be fine right? I think it will just make RBC more stiff.

Best,
Eren.
